= PowerSharp

:psmoduletut: https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/create-standard-library-binary-module?view=powershell-7.1[How to create a Standard Library binary module]
:psclasshelp: https://stephanevg.github.io/powershell/class/module/DATA-How-To-Write-powershell-Modules-with-classes/[How to write Powershell modules with classes]
:psmodmanifest: https://docs.microsoft.com/en-us/powershell/scripting/developer/module/how-to-write-a-powershell-module-manifest?view=powershell-7.1#module-manifest-elements[How to write a Powershell module manifest]
:dotnet-build: link:https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build[dotnet build]

:power: link:power[/power]
:sharp: link:sharp[/sharp]

== Useful Links
- {psmoduletut}
- {psclasshelp}
- {psmodmanifest}

== Project Structure

=== Root
- "meta" files like link:README.adoc[]
- "instructions" like link:build.ps1[]

=== {power}
Contains the root `.psm1` file as well as any additional `.psm1` or `.ps1` files.

[NOTE]
====
To be accessible via type definition (i.e. `[CustomType]`), *Powershell* classes must be loaded via `using module` rather than `Import-Module` (see {psclasshelp})

However, *nested modules* are imported via `Import-Module` (see {psmodmanifest})

As a result, in order for a *Powershell* class to be accessible via type definition it must:

1. Be loaded via `using module` and *not* `Import-Module`
2. Be defined in the *root module* rather than a *nested module*

As a result, it is generally better to define classes as `.cs` files.
====

=== {sharp}
Contains the `.csproj` and `.cs` files used to compile the module's `.dll`.

[NOTE]
====
This is the folder where `dotnet` commands should be executed, such as `dotnet new psmodule` and `dotnet build`.
====

=== link:build[/build]
Contains the *complete compiled & built module*, including:

- The module manifest (`.psd1`)
- The PowerShell files from {power}
- The `.dll` file generated by running `dotnet build` against {sharp}

[NOTE]
====
By default, `.NET` projects are built and placed into the `bin` folder (see {dotnet-build}).

This is still the case for `PowerSharp`: `dotnet build` will generate the `.dll`, etc. in link:sharp/bin/Debug/netstandard2.0/PowerSharp.dll[]

However, we would like to combine the `.dll`-based module components with the `.psm1`-based ones. We have two options to do that:

1. When we build, copy the `.psd1`
====